### ISSUE TITLE
TypeError: object of type 'map' has no len()

### ISSUE THREAD

**Issue by M-Fatih89** [UrbComp/DeepTTE#19]
Hi everyone, I faced this errors when ruining the main.py by sample data files [train 00-04 and test], so, please anyone can suggest to me the way of how to fix this issues?. Thanks for all advance.

Traceback (most recent call last):
  File "C:/....../DeepTTE-master-2/main.py", line 172, in <module>
    run()
  File "C:/........./DeepTTE-master-2/main.py", line 168, in run
    evaluate(model, elogger, config['test_set'], save_result=True)
  File "C:/......./DeepTTE-master-2/main.py", line 119, in evaluate
    data_iter = data_loader.get_loader(input_file, args.batch_size)
  File "C:\.........\DeepTTE-master-2\data_loader.py", line 105, in get_loader
    batch_sampler = BatchSampler(dataset, batch_size)
  File "C:\.........\DeepTTE-master-2\data_loader.py", line 70, in __init__
    self.count = len(dataset)
  File "C:\..........\DeepTTE-master-2\data_loader.py", line 29, in __len__
    return len(self.content)
TypeError: object of type 'map' has no len()

**Comment by M-Fatih89** [comment]
@lucktroy @caow13 @Dawn90 @UrbComp

**Comment by zkjqw139** [comment]
map in python2 return  list,but in python3 return iterator
use list(map(..))

**Comment by M-Fatih89** [comment]
@zkjqw139 Firstly, I want to thank you for your reply, so you are right I figured this issue by the same your suggestion, but I still stuck in the other errors.
I'm not sure if this error belongs to running the code in windows system or other reasons, because I'm a beginner. Let me show the errors: 
![2e8719f2557c3ba9aed67e3ff275b3e](https://user-images.githubusercontent.com/66161950/85652564-c80e4100-b6b3-11ea-851d-5ab63dc4568d.png)

So I hope to find any suggestions, thanks advance.
