### ISSUE TITLE
backward_input can only be called in training mode

### ISSUE THREAD

**Issue by WindyDing** [UrbComp/DeepTTE#6]
Hi, I run the command in readme. 
And I get following error, can you helo me?

`dsc@dsc-OptiPlex-5040:~/paper2/DeepTTE-master$ python main.py --task train  --batch_size 10  --result_file ./result/deeptte.res --pooling_method attention --kernel_size 3 --alpha 0.1 --log_file run_log
/home/dsc/paper2/DeepTTE-master/models/DeepTTE.py:99: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(param.data)
Training on epoch 0
Train on file train_00
main.py:80: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  running_loss += loss.data[0]
 Progress 100.00%, average loss 0.309449195862
Train on file train_01
 Progress 100.00%, average loss 0.314056754112
Train on file train_02
 Progress 100.00%, average loss 0.296637058258
Train on file train_03
 Progress 100.00%, average loss 0.298951894045
main.py:121: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  running_loss += loss.data[0]
Evaluate on file train_04, loss 0.399633079767
Training on epoch 1
Train on file train_00
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    run()
  File "main.py", line 151, in run
    train(model, elogger, train_set = config['train_set'], eval_set = config['eval_set'])
  File "main.py", line 77, in train
    loss.backward()
  File "/home/dsc/.local/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/dsc/.local/lib/python2.7/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: backward_input can only be called in training mode
`

**Comment by caow13** [comment]
@WindyDing have you solved the problem? in line 52 in main.py, the model is indeed switched to train mode. Currently I am not sure which part causes the problem.

**Comment by LoveYourGang** [comment]
Did you use the pytorch-GPU? If so, please check if you turned the mode to evaluation, such as the code "model.eval()". If you did it, you should turn it back when a new epoch begins.
