### ISSUE TITLE
can the code run in python 3.6

### ISSUE THREAD

**Issue by gcy346447065** [UrbComp/DeepTTE#7]
i have tried to run it at win10/cuda9.1.85/anaconda4.5.4/python3.6.5 for some time, but failed. After dealing with some little bugs because of python version from 2 to 3, i'm struggled with the problem:

E:\workbench\DeepTTE-master>python main.py --task train  --batch_size 10  --result_file ./result/deeptte.res --pooling_method attention --kernel_size 3 --alpha 0.1 --log_file run_log
Training on epoch 0
Train on file train_00
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    run()
  File "main.py", line 151, in run
    train(model, elogger, train_set = config['train_set'], eval_set = config['eval_set'])
  File "main.py", line 69, in train
    for idx, (attr, traj) in enumerate(data_iter):
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 239, in __init__
    w.start()
  File "D:\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'MySet.__init__.<locals>.<lambda>'

can anybody give some suggestions??

**Comment by chemjay** [comment]
I also struggled with the same problem. Have you solved it?

**Comment by chemjay** [comment]
Set "num_workers=0"  on the windows platform.
